apiVersion: v1
kind: Service
metadata:
  name: llabdocs-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: llabdocs
