name: Build and Push Helm Chart

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/llabdocs/**'
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Login to Docker Hub (Helm OCI)
        run: echo "$DOCKER_PASSWORD" | helm registry login -u "$DOCKER_USERNAME" --password-stdin docker.io

      - name: Package Helm chart
        run: |
          cd charts
          helm package llabdocs/

      - name: Push Helm chart to Docker Hub
        run: |
          cd charts
          CHART_VERSION=$(helm show chart llabdocs/ | grep '^version:' | awk '{print $2}')
          helm push llabdocs-$CHART_VERSION.tgz oci://docker.io/$DOCKER_USERNAME/llab-helm-charts
