name: Build and Push Helm Chart

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/llabdocs/**'
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Helm login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | helm registry login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin docker.io

      - name: Package Helm chart
        run: |
          cd charts
          helm package llabdocs/
          
      - name: Push to DockerHub
        run: |
          cd charts
          helm push llabdocs-*.tgz oci://docker.io/${{ env.DOCKER_USERNAME }}/llab-helm-charts
